pre-commit:
  parallel: true
  commands:
    generate-shared-types:
      glob: 'shared/**/*.ts'
      run: bun run generate:shared-types
      stage_fixed: true
    oxlint:
      glob: '*.{js,ts,jsx,tsx}'
      run: bunx oxlint --fix {staged_files}
      stage_fixed: true
    oxfmt:
      glob: '*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx,json,jsonc,css,md,yaml,yml}'
      run: bunx oxfmt --no-error-on-unmatched-pattern {staged_files}
      stage_fixed: true
    typecheck:
      run: bun run lint:types
    test:
      run: bun run test
