import { type CompanyCard, type CompanyWorkerType, RoleEnum } from '../types';

const worker = (
    role: 'w' | 'm' | 'both',
    type: CompanyWorkerType = 'unskilled',
    optional = false,
): CompanyCard['workers'][number] => ({
    type,
    optional,
    roles:
        role === 'w'
            ? [RoleEnum.workingClass]
            : role === 'm'
              ? [RoleEnum.middleClass]
              : [RoleEnum.workingClass, RoleEnum.middleClass],
});

// ‼️ generated via scripts/generate-company-cards.ts ‼️

export const capitalistCompanies: CompanyCard[] = [
    {
        id: 'c-college-1',
        name: 'College',
        cost: 16,
        industry: 'education',
        production: 6,
        productionFromAutomation: 2,
        wages: { l1: 10, l2: 20, l3: 30 },
        workers: [worker('both', 'education'), worker('both', 'unskilled')],
    },
    {
        id: 'c-vegetable-farm-1',
        name: 'Vegetable Farm',
        cost: 15,
        industry: 'food',
        production: 5,
        wages: { l1: 20, l2: 25, l3: 30 },
        workers: [
            worker('both', 'unskilled'),
            worker('both', 'unskilled'),
            worker('both', 'unskilled'),
        ],
    },
    {
        id: 'c-radio-station-1',
        name: 'Radio Station',
        cost: 8,
        industry: 'influence',
        production: 2,
        wages: { l1: 10, l2: 15, l3: 20 },
        workers: [worker('both', 'unskilled'), worker('both', 'unskilled')],
    },
    {
        id: 'c-hotel-1',
        name: 'Hotel',
        cost: 15,
        industry: 'luxury',
        production: 7,
        productionFromAutomation: 9,
        wages: { l1: 20, l2: 25, l3: 30 },
        workers: [
            worker('both', 'unskilled'),
            worker('both', 'unskilled'),
            worker('both', 'unskilled'),
        ],
    },
    {
        id: 'c-tv-station-1',
        name: 'TV Station',
        cost: 24,
        industry: 'influence',
        production: 4,
        wages: { l1: 20, l2: 30, l3: 40 },
        workers: [
            worker('both', 'unskilled'),
            worker('both', 'unskilled'),
            worker('both', 'unskilled'),
        ],
    },
    {
        id: 'c-academy-1',
        name: 'Academy',
        cost: 20,
        industry: 'education',
        production: 7,
        wages: { l1: 10, l2: 20, l3: 30 },
        workers: [worker('both', 'education'), worker('both', 'unskilled')],
    },
    {
        id: 'c-car-manufacturer-1',
        name: 'Car Manufacturer',
        cost: 45,
        industry: 'luxury',
        production: 5,
        fullyAutomated: true,
        wages: { l1: 0, l2: 0, l3: 0 },
        workers: [],
    },
    {
        id: 'c-university-1',
        name: 'University',
        cost: 24,
        industry: 'education',
        production: 9,
        productionFromAutomation: 2,
        wages: { l1: 20, l2: 30, l3: 40 },
        workers: [
            worker('both', 'unskilled'),
            worker('both', 'unskilled'),
            worker('both', 'unskilled'),
        ],
    },
    {
        id: 'c-fast-food-chain-1',
        name: 'Fast Food Chain',
        cost: 8,
        industry: 'food',
        production: 3,
        wages: { l1: 10, l2: 15, l3: 20 },
        workers: [worker('both', 'food'), worker('both', 'unskilled')],
    },
    {
        id: 'c-electronics-manufacturer-1',
        name: 'Electronics Manufacturer',
        cost: 25,
        industry: 'luxury',
        production: 3,
        fullyAutomated: true,
        wages: { l1: 0, l2: 0, l3: 0 },
        workers: [],
    },
    {
        id: 'c-fish-farm-1',
        name: 'Fish Farm',
        cost: 20,
        industry: 'food',
        production: 6,
        productionFromAutomation: 1,
        wages: { l1: 25, l2: 30, l3: 35 },
        workers: [
            worker('both', 'unskilled'),
            worker('both', 'unskilled'),
            worker('both', 'unskilled'),
        ],
    },
    {
        id: 'c-publishing-house-1',
        name: 'Publishing House',
        cost: 12,
        industry: 'influence',
        production: 3,
        wages: { l1: 20, l2: 25, l3: 30 },
        workers: [
            worker('both', 'influence'),
            worker('both', 'unskilled'),
            worker('both', 'unskilled'),
        ],
    },
    {
        id: 'c-clinic-1',
        name: 'Clinic',
        cost: 16,
        industry: 'healthcare',
        production: 6,
        productionFromAutomation: 2,
        wages: { l1: 10, l2: 20, l3: 30 },
        workers: [worker('both', 'unskilled'), worker('both', 'unskilled')],
    },
    {
        id: 'c-stadium-1',
        name: 'Stadium',
        cost: 20,
        industry: 'luxury',
        production: 8,
        productionFromAutomation: 3,
        wages: { l1: 25, l2: 30, l3: 35 },
        workers: [
            worker('both', 'luxury'),
            worker('both', 'unskilled'),
            worker('both', 'unskilled'),
        ],
    },
    {
        id: 'c-hospital-1',
        name: 'Hospital',
        cost: 20,
        industry: 'healthcare',
        production: 7,
        wages: { l1: 10, l2: 20, l3: 30 },
        workers: [worker('both', 'healthcare'), worker('both', 'unskilled')],
    },
    {
        id: 'c-medical-village-1',
        name: 'Medical Village',
        cost: 24,
        industry: 'healthcare',
        production: 9,
        productionFromAutomation: 2,
        wages: { l1: 20, l2: 30, l3: 40 },
        workers: [
            worker('both', 'healthcare'),
            worker('both', 'unskilled'),
            worker('both', 'unskilled'),
        ],
    },
    {
        id: 'c-supermarket-1',
        name: 'Supermarket',
        cost: 16,
        industry: 'food',
        production: 4,
        productionFromAutomation: 1,
        wages: { l1: 15, l2: 20, l3: 25 },
        workers: [worker('both', 'food'), worker('both', 'unskilled')],
    },
    {
        id: 'c-shopping-mall-1',
        name: 'Shopping Mall',
        cost: 16,
        industry: 'luxury',
        production: 6,
        productionFromAutomation: 2,
        wages: { l1: 15, l2: 20, l3: 25 },
        workers: [worker('both', 'luxury'), worker('both', 'unskilled')],
    },
    {
        id: 'c-lobbying-firm-1',
        name: 'Lobbying Firm',
        cost: 16,
        industry: 'influence',
        production: 3,
        wages: { l1: 10, l2: 20, l3: 30 },
        workers: [worker('both', 'influence'), worker('both', 'unskilled')],
    },
    {
        id: 'c-institute-of-technology-1',
        name: 'Institute of Technology',
        cost: 20,
        industry: 'education',
        production: 8,
        productionFromAutomation: 3,
        wages: { l1: 20, l2: 30, l3: 40 },
        workers: [
            worker('both', 'education'),
            worker('both', 'unskilled'),
            worker('both', 'unskilled'),
        ],
    },
    {
        id: 'c-automated-grain-farm-1',
        name: 'Automated Grain Farm',
        cost: 25,
        industry: 'food',
        production: 2,
        fullyAutomated: true,
        wages: { l1: 0, l2: 0, l3: 0 },
        workers: [],
    },
    {
        id: 'c-fashion-company-1',
        name: 'Fashion Company',
        cost: 8,
        industry: 'luxury',
        production: 4,
        productionFromAutomation: 2,
        wages: { l1: 10, l2: 15, l3: 20 },
        workers: [worker('both', 'unskilled'), worker('both', 'unskilled')],
    },
    {
        id: 'c-automated-dairy-farm-1',
        name: 'Automated Dairy Farm',
        cost: 45,
        industry: 'food',
        production: 3,
        fullyAutomated: true,
        wages: { l1: 0, l2: 0, l3: 0 },
        workers: [],
    },
    {
        id: 'c-pharmaceutical-company-1',
        name: 'Pharmaceutical Company',
        cost: 20,
        industry: 'healthcare',
        production: 8,
        productionFromAutomation: 3,
        wages: { l1: 20, l2: 30, l3: 40 },
        workers: [
            worker('both', 'healthcare'),
            worker('both', 'unskilled'),
            worker('both', 'unskilled'),
        ],
    },
    {
        id: 'c-clinic-2',
        name: 'Clinic',
        cost: 16,
        industry: 'healthcare',
        production: 6,
        productionFromAutomation: 2,
        wages: { l1: 10, l2: 20, l3: 30 },
        workers: [worker('both', 'healthcare'), worker('both', 'unskilled')],
    },
    {
        id: 'c-college-2',
        name: 'College',
        cost: 16,
        industry: 'education',
        production: 6,
        productionFromAutomation: 2,
        wages: { l1: 10, l2: 20, l3: 30 },
        workers: [worker('both', 'education'), worker('both', 'unskilled')],
    },
    {
        id: 'c-shopping-mall-2',
        name: 'Shopping Mall',
        cost: 16,
        industry: 'luxury',
        production: 6,
        productionFromAutomation: 2,
        wages: { l1: 15, l2: 20, l3: 25 },
        workers: [worker('both', 'luxury'), worker('both', 'unskilled')],
    },
    {
        id: 'c-supermarket-2',
        name: 'Supermarket',
        cost: 16,
        industry: 'food',
        production: 4,
        productionFromAutomation: 1,
        wages: { l1: 15, l2: 20, l3: 25 },
        workers: [worker('both', 'food'), worker('both', 'unskilled')],
    },
];

export const middleClassCompanies: CompanyCard[] = [
    {
        id: 'm-jewelry-store-1',
        name: 'Jewelry Store',
        cost: 16,
        industry: 'luxury',
        production: 4,
        wages: { l1: 0, l2: 0, l3: 0 },
        workers: [worker('m', 'luxury'), worker('m', 'unskilled')],
    },
    {
        id: 'm-regional-radio-station-1',
        name: 'Regional Radio Station',
        cost: 20,
        industry: 'influence',
        production: 2,
        productionFromOptionalWorkers: 2,
        wages: { l1: 9, l2: 12, l3: 15 },
        workers: [worker('m', 'influence'), worker('w', 'influence', true)],
    },
    {
        id: 'm-doctors-office-1',
        name: "Doctor's Office",
        cost: 12,
        industry: 'healthcare',
        production: 2,
        productionFromOptionalWorkers: 2,
        wages: { l1: 6, l2: 8, l3: 10 },
        workers: [worker('m', 'healthcare'), worker('w', 'unskilled', true)],
    },
    {
        id: 'm-pr-agency-1',
        name: 'PR Agency',
        cost: 20,
        industry: 'influence',
        production: 3,
        wages: { l1: 0, l2: 0, l3: 0 },
        workers: [worker('m', 'influence'), worker('m', 'unskilled')],
    },
    {
        id: 'm-fast-food-restaurant-1',
        name: 'Fast Food Restaurant',
        cost: 20,
        industry: 'food',
        production: 3,
        wages: { l1: 0, l2: 0, l3: 0 },
        workers: [worker('m', 'food'), worker('m', 'unskilled')],
    },
    {
        id: 'm-tutoring-company-1',
        name: 'Tutoring Company',
        cost: 12,
        industry: 'education',
        production: 2,
        productionFromOptionalWorkers: 2,
        wages: { l1: 6, l2: 8, l3: 10 },
        workers: [worker('m', 'education'), worker('w', 'unskilled', true)],
    },
    {
        id: 'm-private-school-1',
        name: 'Private School',
        cost: 20,
        industry: 'education',
        production: 2,
        productionFromOptionalWorkers: 4,
        wages: { l1: 9, l2: 12, l3: 15 },
        workers: [worker('m', 'education'), worker('w', 'education', true)],
    },
    {
        id: 'm-training-center-1',
        name: 'Training Center',
        cost: 16,
        industry: 'education',
        production: 4,
        wages: { l1: 0, l2: 0, l3: 0 },
        workers: [worker('m', 'education'), worker('m', 'unskilled')],
    },
    {
        id: 'm-convenience-store-1',
        name: 'Convenience Store',
        cost: 14,
        industry: 'food',
        production: 2,
        productionFromOptionalWorkers: 1,
        wages: { l1: 6, l2: 8, l3: 10 },
        workers: [worker('m', 'food'), worker('w', 'unskilled', true)],
    },
    {
        id: 'm-medical-laboratory-1',
        name: 'Medical Laboratory',
        cost: 20,
        industry: 'healthcare',
        production: 2,
        productionFromOptionalWorkers: 4,
        wages: { l1: 9, l2: 12, l3: 15 },
        workers: [worker('m', 'healthcare'), worker('w', 'healthcare', true)],
    },
    {
        id: 'm-electronics-store-1',
        name: 'Electronics Store',
        cost: 20,
        industry: 'luxury',
        production: 2,
        productionFromOptionalWorkers: 4,
        wages: { l1: 9, l2: 12, l3: 15 },
        workers: [worker('m', 'luxury'), worker('w', 'luxury', true)],
    },
    {
        id: 'm-local-newspaper-1',
        name: 'Local Newspaper',
        cost: 14,
        industry: 'influence',
        production: 2,
        productionFromOptionalWorkers: 1,
        wages: { l1: 6, l2: 8, l3: 10 },
        workers: [worker('m', 'influence'), worker('w', 'unskilled', true)],
    },
    {
        id: 'm-game-store-1',
        name: 'Game Store',
        cost: 12,
        industry: 'luxury',
        production: 2,
        productionFromOptionalWorkers: 2,
        wages: { l1: 6, l2: 8, l3: 10 },
        workers: [worker('m', 'luxury'), worker('w', 'unskilled', true)],
    },
    {
        id: 'm-organic-farm-1',
        name: 'Organic Farm',
        cost: 20,
        industry: 'food',
        production: 2,
        productionFromOptionalWorkers: 2,
        wages: { l1: 9, l2: 12, l3: 15 },
        workers: [worker('m', 'food'), worker('w', 'food', true)],
    },
    {
        id: 'm-doctors-office-2',
        name: "Doctor's Office",
        cost: 12,
        industry: 'healthcare',
        production: 2,
        productionFromOptionalWorkers: 2,
        wages: { l1: 6, l2: 8, l3: 10 },
        workers: [worker('m', 'healthcare'), worker('w', 'unskilled', true)],
    },
    {
        id: 'm-convenience-store-2',
        name: 'Convenience Store',
        cost: 14,
        industry: 'food',
        production: 2,
        productionFromOptionalWorkers: 1,
        wages: { l1: 6, l2: 8, l3: 10 },
        workers: [worker('m', 'food'), worker('w', 'unskilled', true)],
    },
    {
        id: 'm-pharmacy-1',
        name: 'Pharmacy',
        cost: 16,
        industry: 'healthcare',
        production: 4,
        wages: { l1: 0, l2: 0, l3: 0 },
        workers: [worker('m', 'healthcare'), worker('m', 'unskilled')],
    },
];

export const stateCompanies: CompanyCard[] = [
    {
        id: 's-university-hospital-1',
        name: 'University Hospital',
        cost: 30,
        industry: 'healthcare',
        production: 6,
        wages: { l1: 25, l2: 30, l3: 35 },
        workers: [
            worker('both', 'healthcare'),
            worker('both', 'unskilled'),
            worker('both', 'unskilled'),
        ],
    },
    {
        id: 's-technical-university-1',
        name: 'Technical University',
        cost: 30,
        industry: 'education',
        production: 6,
        wages: { l1: 25, l2: 30, l3: 35 },
        workers: [
            worker('both', 'education'),
            worker('both', 'unskilled'),
            worker('both', 'unskilled'),
        ],
    },
    {
        id: 's-national-public-broadcasting-1',
        name: 'National Public Broadcasting',
        cost: 30,
        industry: 'influence',
        production: 4,
        wages: { l1: 25, l2: 30, l3: 35 },
        workers: [
            worker('both', 'influence'),
            worker('both', 'unskilled'),
            worker('both', 'unskilled'),
        ],
    },
    {
        id: 's-public-hospital-1',
        name: 'Public Hospital',
        cost: 20,
        industry: 'healthcare',
        production: 4,
        wages: { l1: 15, l2: 20, l3: 25 },
        workers: [worker('both', 'healthcare'), worker('both', 'unskilled')],
    },
    {
        id: 's-public-university-1',
        name: 'Public University',
        cost: 20,
        industry: 'education',
        production: 4,
        wages: { l1: 15, l2: 20, l3: 25 },
        workers: [worker('both', 'education'), worker('both', 'unskilled')],
    },
    {
        id: 's-regional-tv-station-1',
        name: 'Regional TV Station',
        cost: 20,
        industry: 'influence',
        production: 4,
        wages: { l1: 15, l2: 20, l3: 25 },
        workers: [worker('both', 'influence'), worker('both', 'unskilled')],
    },
    {
        id: 's-public-hospital-2',
        name: 'Public Hospital',
        cost: 20,
        industry: 'healthcare',
        production: 4,
        wages: { l1: 15, l2: 20, l3: 25 },
        workers: [worker('both', 'healthcare'), worker('both', 'unskilled')],
    },
    {
        id: 's-public-university-2',
        name: 'Public University',
        cost: 20,
        industry: 'education',
        production: 4,
        wages: { l1: 15, l2: 20, l3: 25 },
        workers: [worker('both', 'education'), worker('both', 'unskilled')],
    },
    {
        id: 's-regional-tv-station-2',
        name: 'Regional TV Station',
        cost: 20,
        industry: 'influence',
        production: 4,
        wages: { l1: 15, l2: 20, l3: 25 },
        workers: [worker('both', 'influence'), worker('both', 'unskilled')],
    },
];
